export const BEGINNER_NROFSCRAMBLES = 25;
export const INTERMEDIATE_NROFSCRAMBLES = 50;
export const PRO_NROFSCRAMBLES = 150;
export const ADAGIO_SCRAMBLESPEED = 500;
export const MODERATO_SCRAMBLESPEED = 350;
export const ALLEGRO_SCRAMBLESPEED = 200;
